email: alexmoxonn@gmail.com
password: 

disableAntiLock: FALSE

remote: TRUE

experienceLevel:
 internship: FALSE
 entry: FALSE
 associate: TRUE
 mid-senior level: TRUE
 director: FALSE
 executive: FALSE

jobTypes:
 full-time: TRUE
 contract: TRUE
 part-time: FALSE
 temporary: FALSE
 internship: FALSE
 other: FALSE
 volunteer: FALSE

date:
 all time: FALSE
 month: FALSE
 week: FALSE
 24 hours: TRUE

locations:
 remote: TRUE

uploads:
 resume: C:\Users\mox\Desktop\res\Alex_Moxon_Resume.pdf

# ------- Questions Section ------- #
checkboxes:
 driversLicense: TRUE
 requireVisa: FALSE
 legallyAuthorized: TRUE
 urgentFill: TRUE
 commute: FALSE
 degreeCompleted:
  - High School Diploma
  - Bachelor's Degree

 backgroundCheck: TRUE

universityGpa: 3.4

languages:
 english: Native or bilingual

industry:
 Accounting/Auditing: 0
 Administrative : 0
 Advertising : 0
 Analyst : 0
 Art/Creative: 0
 Business Development: 0
 Consulting: 0
 Customer Service: 0
 Distribution Design: 0
 Education: 0
 Engineering: 0
 Finance: 0
 General Business: 0
 Health Care Provider: 0
 Human Resources: 0
 Information Technology: 0
 Legal: 0
 Management: 0
 Manufacturing: 0
 Marketing: 0
 Public Relations: 0
 Purchasing: 0
 Product Management: 0
 Project Management: 0
 Production: 0
 Quality Assurance: 0
 Research: 0
 Sales: 0
 Science: 0
 Strategy/Planning: 0
 Supply Chain: 0
 Training: 0
 Writing/Editing: 0
 Django: 4
 Python: 4
 Amazon Web Services: 2
 GCP: 2
 SQL: 3
 Terraform: 2
 Advertising: 2
 C++: 2
 default: 2

 technology:
 default: 2
 API Development: 3

personalInfo:
 First Name: Alex
 Last Name: Moxon
 Phone Country Code: United States (+1)
 Mobile Phone Number: 5306802944
 Street Address: 2060 Amanday Way
 City: Chico
 State: California
 Zip: 95928
 Linkedin: https://www.linkedin.com/in/alex-moxon-b829a312a/
 Website: https://paramox.io/

eeo:
 gender: Male
 race: None
 vetran: None
 disability: None
 citizenship: U.S.

